services:
  app:
    entrypoint:
    - sleep
    - infinity
    # image: silkeh/clang:15
    build: .
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    network_mode: bridge
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

